# Generated by Django 3.1 on 2020-10-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200904_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='menu/offers/images')),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_daily_offer', models.BooleanField(default=False)),
                ('for_all_products', models.BooleanField(default=False)),
                ('applicable_quantity', models.IntegerField()),
                ('exclude_products', models.ManyToManyField(related_name='exclude_products', to='menu.Product')),
                ('products', models.ManyToManyField(related_name='products', to='menu.Product')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
