# Generated by Django 3.1 on 2020-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='exclude_products', to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='menu.Product'),
        ),
    ]
