# Generated by Django 3.1 on 2021-02-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20201019_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
