# Generated by Django 3.1 on 2021-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Namaste Ongole', max_length=100)),
                ('area', models.CharField(default='Kothapatnam (m) pallepalem (v)', max_length=100)),
                ('city', models.CharField(default='Ongole', max_length=20)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('gst', models.IntegerField(default=5)),
                ('delivery_charges', models.IntegerField(default=25)),
            ],
        ),
    ]
