# Generated by Django 3.1 on 2020-10-02 13:33

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'CASH_ON_DELIVERY'), (2, 'DELIVERY'), (3, 'PICK_UP')], default=order.models.OrderTypes['NONE']),
        ),
    ]
