# Generated by Django 3.1 on 2020-10-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20201019_1234'),
        ('order', '0006_auto_20201002_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.offer'),
        ),
    ]
